language: c
env:
  matrix:
    - CI_ENV=gcc
    - CI_ENV=clang
    - CI_ENV=gcov
  global:
    - secure: "QDuBYD70tDc+2v4WdNEbmv4BE/jVHrDp9QZ+a7ZYPgnUe5hRnKfKSOhsuzGDRkMBnrJFbaeFITrGY7WQKcwLcMxKq11/Lk6Of9ai+TxN4VY+p1yt3Poz/7pDg7bVTPepnEgVUjjLQC8UoGXo7jaLscqJuU3vAl/LVQ9igC8TwKQ="
before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  # Build tools
  - sudo apt-get install -qq gcc-4.8 g++-4.8 ragel cmake make
  # Coverage
  - sudo apt-get install lcov libglib2.0-dev
  - sudo pip install cpp-coveralls
  # Plugins
  - sudo apt-get install libbz2-dev liblzma-dev liblzo2-dev libsnappy-dev zlib1g-dev
  # - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
script: "./.travis.sh"
